algoritmo "13-laco-para.alg"
// Função : Exemplo de laço de repetição usando o PARA
// Autor : Fábio Corrêa
// Data : 26/04/2021
// Seção de Declarações 
var
   CONT: inteiro
inicio
// Seção de Comandos 
   escreval("***********************************")
   escreval("Exemplo de laço de repetição - PARA")
   escreval("***********************************")
   escreval("")
   
   para CONT de 1 ate 10 faca
        escreval (CONT, "a linha")
   fimpara
   
fimalgoritmo
